#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
# SPDX-License-Identifier: CC0-1.0

# Create SBOM ZIP archive containing all 3 layers
# Usage: create-sbom-zip.sh <project-name> <version>

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../ci/output.sh"

main() {
  local PROJECT_NAME="${1:-$(basename "$(git config --get remote.origin.url)" .git)}"
  local VERSION="${2:-unknown}"
  VERSION="${VERSION#v}" # Remove 'v' prefix if present

  # Count SBOMs to determine if we need to create a ZIP
  local SBOM_COUNT
  SBOM_COUNT=$(find . -maxdepth 1 -name '*-sbom.*.json' 2>/dev/null | wc -l)
  if [[ -d "./sbom-artifacts" ]]; then
    SBOM_COUNT=$((SBOM_COUNT + $(find ./sbom-artifacts -name '*-container-sbom.*.json' 2>/dev/null | wc -l)))
  fi

  if [[ "$SBOM_COUNT" -eq 0 ]]; then
    printf "No SBOMs found, skipping ZIP creation\n"
    exit 0
  fi

  printf "Creating SBOM zip archive with all 3 layers\n"
  local SBOM_ZIP
  SBOM_ZIP=$(ci_sbom_zip_name "$PROJECT_NAME" "$VERSION")

  # Add source and artifact layer SBOMs to ZIP
  # Matches any layer generated by generate-sbom.sh (pom, package, gradle, jar, tararchive, etc.)
  for sbom in *-sbom.spdx.json *-sbom.cyclonedx.json; do
    if [[ -f "$sbom" ]]; then
      zip "$SBOM_ZIP" "$sbom"
      printf "  Added: %s\n" "$sbom"
    fi
  done

  # Add container SBOMs to zip if they exist (Layer 3)
  if [[ -d "./sbom-artifacts" ]]; then
    for sbom in ./sbom-artifacts/*-container-sbom.*.json; do
      if [[ -f "$sbom" ]]; then
        zip -j "$SBOM_ZIP" "$sbom"
        printf "  Added: %s\n" "$(basename "$sbom")"
      fi
    done
  fi

  printf "SBOM ZIP contents:\n"
  unzip -l "$SBOM_ZIP"

  printf "Created SBOM ZIP: %s\n" "$SBOM_ZIP"
}

main "$@"
