# SPDX-FileCopyrightText: 2025 The Reusable CI Authors
#
# SPDX-License-Identifier: CC0-1.0

# Example: Android App Build Workflow (for development/CI builds)
# This builds Android variants during development

name: Build Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    uses: diggsweden/reusable-ci/.github/workflows/build-gradle-android-variants.yml@v2
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      java-version: "21"
      jdk-distribution: "zulu"
      build-module: "app"
      product-flavor: "demo"
      build-types: "debug,release"
      include-aab: true
      artifact-name-prefix: "testing_store"
      include-date-stamp: true
      enable-signing: false # Set to true for signed builds
