# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

# Release Dev Workflow
#
# This workflow builds the Android app and uploads to Google Play internal track for testing.
# Triggered manually via workflow_dispatch (GitHub Actions UI).
#
# How to use:
# 1. Go to Actions tab in GitHub
# 2. Select "Release Dev Workflow"
# 3. Click "Run workflow"
# 4. Select branch to build from
# 5. Click "Run workflow"
#
# Created artifacts:
# - AAB uploaded to Google Play internal track
#
# This mirrors the iOS release-dev-workflow which uploads to TestFlight.
# For Android, the equivalent is Google Play's internal testing track.

name: Release Dev Workflow

on:
  workflow_dispatch:

concurrency:
  group: release-dev-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    uses: diggsweden/reusable-ci/.github/workflows/build-gradle-android.yml@main
    permissions:
      contents: read
    secrets: inherit
    with:
      java-version: "21"
      build-module: app
      product-flavor: demo
      build-types: release
      include-aab: true
      enable-signing: true
      artifact-name-prefix: dev
      include-date-stamp: false

  upload-play-store:
    needs: build
    uses: diggsweden/reusable-ci/.github/workflows/publish-google-play.yml@main
    permissions:
      contents: read
    secrets: inherit
    with:
      # Artifact name format: "{prefix} - {repo-name} - {flavor} - AAB release"
      # Adjust to match your repository name and flavor
      aab-artifact-name: dev - my-android-app - demo - AAB release
      package-name: com.example.myapp
      track: internal
      status: completed
