// SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government
// SPDX-License-Identifier: EUPL-1.2 OR GPL-3.0-or-later

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/urfave/cli/v3"
)

// Render returns the full docs/cli-reference.md body for root.
//
// The render walks every visible subcommand (depth-first, alphabetical
// within each level), emits one heading per command with its usage,
// options table, and breadcrumb path. The result is byte-stable: re-
// running on the same root produces the same output.
func Render(root *cli.Command) string {
	var b strings.Builder //nolint:varnamelen // idiomatic short name (testing/http/io conventions).

	// REUSE-IgnoreStart
	_, _ = fmt.Fprintln(&b, "<!--")
	_, _ = fmt.Fprintln(&b, "SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government")
	_, _ = fmt.Fprintln(&b, "SPDX-License-Identifier: CC0-1.0")
	_, _ = fmt.Fprintln(&b, "")
	// REUSE-IgnoreEnd
	_, _ = fmt.Fprintln(&b, "Auto-generated by `cmd/gen-cli-reference`. Do not edit by hand.")
	_, _ = fmt.Fprintln(&b, "Run `go run ./cmd/gen-cli-reference > docs/cli-reference.md` to refresh.")
	_, _ = fmt.Fprintln(&b, "-->")
	_, _ = fmt.Fprintln(&b)
	_, _ = fmt.Fprintln(&b, "# `reusable-ci` reference")
	_, _ = fmt.Fprintln(&b)
	_, _ = fmt.Fprintln(&b, "This document is the canonical surface of the `reusable-ci` binary.")
	_, _ = fmt.Fprintln(&b)
	_, _ = fmt.Fprintln(&b, "Every command supports `--help`. Global flags (`--quiet`, `--log-level`, `--format`, `--json`)")
	_, _ = fmt.Fprintln(&b, "are accepted on every subcommand.")
	_, _ = fmt.Fprintln(&b)

	// Top-level table of contents.
	_, _ = fmt.Fprintln(&b, "## Command groups")
	_, _ = fmt.Fprintln(&b)

	for _, sub := range visibleCommands(root.Commands) {
		_, _ = fmt.Fprintf(&b, "- [`%s`](#%s) — %s\n", sub.Name, slug(root.Name+" "+sub.Name), escapeText(sub.Usage))
	}

	_, _ = fmt.Fprintln(&b)

	for _, sub := range visibleCommands(root.Commands) {
		renderSubtree(&b, sub, []string{root.Name, sub.Name}, 2)
	}

	return strings.TrimRight(b.String(), "\n") + "\n"
}

func renderSubtree(b *strings.Builder, cmd *cli.Command, breadcrumb []string, level int) { //nolint:varnamelen // idiomatic short name (testing/http/io conventions).
	_, _ = fmt.Fprintf(b, "%s `%s`\n", strings.Repeat("#", level), strings.Join(breadcrumb, " "))
	_, _ = fmt.Fprintln(b)

	if cmd.Usage != "" {
		_, _ = fmt.Fprintln(b, escapeText(cmd.Usage))
		_, _ = fmt.Fprintln(b)
	}

	if cmd.ArgsUsage != "" {
		_, _ = fmt.Fprintf(b, "**Usage:** `%s %s`\n\n", strings.Join(breadcrumb, " "), cmd.ArgsUsage)
	}

	if len(cmd.Flags) > 0 {
		_, _ = fmt.Fprintln(b, "| Flag | Description | Env vars |")
		_, _ = fmt.Fprintln(b, "|------|-------------|----------|")

		for _, f := range cmd.Flags {
			n, usage, sources := flagFields(f)
			if n == "" {
				continue
			}

			_, _ = fmt.Fprintf(b, "| `--%s` | %s | %s |\n", n, escapeCell(usage), escapeCell(sources))
		}

		_, _ = fmt.Fprintln(b)
	}

	for _, sub := range visibleCommands(cmd.Commands) {
		renderSubtree(b, sub, append(append([]string{}, breadcrumb...), sub.Name), level+1)
	}
}

// flagFields extracts (name, usage, sources) from a cli.Flag without
// reflection — uses the small docOnlyFlag interface the urfave/cli
// flag types all satisfy.
func flagFields(f cli.Flag) (string, string, string) { //nolint:varnamelen // idiomatic short name (testing/http/io conventions).
	var name, usage, sources string

	if d, ok := f.(interface {
		Names() []string
	}); ok {
		names := d.Names()
		if len(names) > 0 {
			name = names[0]
		}
	}
	// Use the public Usage field via DocGenerationFlag if available.
	if d, ok := f.(cli.DocGenerationFlag); ok {
		usage = d.GetUsage()
	}

	if usage == "" && name != "" {
		usage = "Sets " + strings.ReplaceAll(name, "-", " ") + "."
	}
	// Sources rendering: each flag type stores its EnvVars via its
	// Sources field. We only need the env-var subset.
	if d, ok := f.(interface {
		GetEnvVars() []string
	}); ok {
		envs := d.GetEnvVars()
		if len(envs) > 0 {
			parts := make([]string, len(envs))
			for i, e := range envs {
				parts[i] = "`$" + e + "`"
			}

			sources = strings.Join(parts, ", ")
		}
	}

	if sources == "" {
		sources = "n/a"
	}

	return name, usage, sources
}

func visibleCommands(cmds []*cli.Command) []*cli.Command {
	out := make([]*cli.Command, 0, len(cmds))
	for _, c := range cmds {
		if c.Hidden {
			continue
		}

		out = append(out, c)
	}

	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })

	return out
}

// slug turns a command name into an anchor-safe identifier.
func slug(name string) string {
	var b strings.Builder //nolint:varnamelen // idiomatic short name (testing/http/io conventions).

	for _, r := range strings.ToLower(name) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-':
			b.WriteRune(r)
		case r == ' ', r == '_':
			b.WriteRune('-')
		}
	}

	return b.String()
}

// escapeCell renders a string for a markdown table cell. Pipe and
// newline characters break the row, so they get escaped / collapsed.
func escapeCell(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "|", `\|`)

	return s
}

func escapeText(s string) string {
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	s = strings.ReplaceAll(s, "*", `\*`)

	return s
}
