// SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government
// SPDX-License-Identifier: EUPL-1.2 OR GPL-3.0-or-later

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/urfave/cli/v3"
)

// Render returns the full docs/cli-reference.md body for root.
//
// The render walks every visible subcommand (depth-first, alphabetical
// within each level), emits one heading per command with its usage,
// options table, and breadcrumb path. The result is byte-stable: re-
// running on the same root produces the same output.
func Render(root *cli.Command) string {
	var b strings.Builder //nolint:varnamelen // idiomatic short name (testing/http/io conventions).

	// REUSE-IgnoreStart
	_, _ = fmt.Fprintln(&b, "<!--")
	_, _ = fmt.Fprintln(&b, "SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government")
	_, _ = fmt.Fprintln(&b, "SPDX-License-Identifier: CC0-1.0")
	_, _ = fmt.Fprintln(&b, "")
	// REUSE-IgnoreEnd
	_, _ = fmt.Fprintln(&b, "Auto-generated by `cmd/gen-cli-reference`. Do not edit by hand.")
	_, _ = fmt.Fprintln(&b, "Run `go run ./cmd/gen-cli-reference > docs/cli-reference.md` to refresh.")
	_, _ = fmt.Fprintln(&b, "-->")
	_, _ = fmt.Fprintln(&b)
	_, _ = fmt.Fprintln(&b, "# `reusable-ci` reference")
	_, _ = fmt.Fprintln(&b)
	_, _ = fmt.Fprintln(&b, "This document is the canonical surface of the `reusable-ci` binary.")
	_, _ = fmt.Fprintln(&b)
	_, _ = fmt.Fprintln(&b, "Every command supports `--help`. Global flags (`--quiet`, `--log-level`, `--format`, `--json`,")
	_, _ = fmt.Fprintln(&b, "`--provider`, `--runner`) are accepted on every subcommand.")
	_, _ = fmt.Fprintln(&b)
	_, _ = fmt.Fprintln(&b, "Value resolution is one fixed precedence everywhere: explicit flag, then (where a")
	_, _ = fmt.Fprintln(&b, "command supports it) the `$REUSABLE_CI_PLAN` plan-file field for the command's scope,")
	_, _ = fmt.Fprintln(&b, "then the environment variables listed per flag, then the flag default.")
	_, _ = fmt.Fprintln(&b)

	// Top-level table of contents.
	_, _ = fmt.Fprintln(&b, "## Command groups")
	_, _ = fmt.Fprintln(&b)

	for _, sub := range visibleCommands(root.Commands) {
		_, _ = fmt.Fprintf(&b, "- [`%s`](#%s) — %s\n", sub.Name, slug(root.Name+" "+sub.Name), escapeText(sub.Usage))
	}

	_, _ = fmt.Fprintln(&b)

	for _, sub := range visibleCommands(root.Commands) {
		renderSubtree(&b, sub, []string{root.Name, sub.Name}, 2)
	}

	return strings.TrimRight(b.String(), "\n") + "\n"
}

func renderSubtree(b *strings.Builder, cmd *cli.Command, breadcrumb []string, level int) { //nolint:varnamelen // idiomatic short name (testing/http/io conventions).
	_, _ = fmt.Fprintf(b, "%s `%s`\n", strings.Repeat("#", level), strings.Join(breadcrumb, " "))
	_, _ = fmt.Fprintln(b)

	if cmd.Usage != "" {
		_, _ = fmt.Fprintln(b, escapeText(cmd.Usage))
		_, _ = fmt.Fprintln(b)
	}

	// The Description holds the long help — decision guides ("which verb do I
	// want?") and EXAMPLE blocks. It is preformatted terminal text, so render it
	// verbatim in a fenced block rather than as markdown; this is the one place a
	// reader browses the whole surface, so the examples belong here, not only in
	// `--help`. No Description contains a code fence (guarded), so ``` is safe.
	if desc := strings.TrimRight(cmd.Description, "\n"); desc != "" {
		_, _ = fmt.Fprintln(b, "```")
		_, _ = fmt.Fprintln(b, desc)
		_, _ = fmt.Fprintln(b, "```")
		_, _ = fmt.Fprintln(b)
	}

	if cmd.ArgsUsage != "" {
		_, _ = fmt.Fprintf(b, "**Usage:** `%s %s`\n\n", strings.Join(breadcrumb, " "), cmd.ArgsUsage)
	}

	if len(cmd.Flags) > 0 {
		_, _ = fmt.Fprintln(b, "| Flag | Description | Env vars |")
		_, _ = fmt.Fprintln(b, "|------|-------------|----------|")

		for _, declared := range cmd.Flags {
			primary, usage, sources := flagFields(declared)
			if primary == "" {
				continue
			}

			_, _ = fmt.Fprintf(b, "| %s | %s | %s |\n",
				flagNameCell(declared, primary), escapeCell(usage), escapeCell(sources))
		}

		_, _ = fmt.Fprintln(b)
	}

	for _, sub := range visibleCommands(cmd.Commands) {
		renderSubtree(b, sub, append(append([]string{}, breadcrumb...), sub.Name), level+1)
	}
}

// flagNameCell renders a flag's primary name followed by any aliases, e.g.
// "`--temp-dir`, `--runner-temp`".
//
// Aliases are part of the CLI contract: they are how a rename stays
// non-breaking, so a reference that omits them documents a surface narrower
// than the one that actually exists — and tells a caller still passing the
// old name that their flag is gone. `--help` has always listed them; this
// keeps the generated reference in step.
func flagNameCell(flag cli.Flag, primary string) string {
	names, ok := flag.(interface{ Names() []string })
	if !ok {
		return "`--" + primary + "`"
	}

	cells := make([]string, 0, len(names.Names()))
	for _, n := range names.Names() {
		if n != "" {
			cells = append(cells, "`--"+n+"`")
		}
	}

	if len(cells) == 0 {
		return "`--" + primary + "`"
	}

	return strings.Join(cells, ", ")
}

// flagFields extracts (name, usage, sources) from a cli.Flag without
// reflection — uses the small docOnlyFlag interface the urfave/cli
// flag types all satisfy.
func flagFields(f cli.Flag) (string, string, string) { //nolint:varnamelen // idiomatic short name (testing/http/io conventions).
	var name, usage string

	if d, ok := f.(interface {
		Names() []string
	}); ok {
		names := d.Names()
		if len(names) > 0 {
			name = names[0]
		}
	}
	// Use the public Usage field via DocGenerationFlag if available.
	if d, ok := f.(cli.DocGenerationFlag); ok {
		usage = d.GetUsage()
	}

	if usage == "" && name != "" {
		usage = "Sets " + strings.ReplaceAll(name, "-", " ") + "."
	}
	// Advertise required-ness so the reference matches `--help`; both keep
	// the marker in lockstep off the flag's own Required property.
	if rf, ok := f.(cli.RequiredFlag); ok && rf.IsRequired() {
		usage = strings.TrimRight(usage, " ") + " (required)"
	}

	return name, usage, flagSources(f)
}

// flagSources renders a flag's env-var subset as a markdown cell, or "n/a"
// when the flag has none. Each flag type stores its EnvVars via its Sources
// field.
func flagSources(f cli.Flag) string {
	envFlag, ok := f.(interface {
		GetEnvVars() []string
	})
	if !ok || len(envFlag.GetEnvVars()) == 0 {
		return "n/a"
	}

	parts := make([]string, 0, len(envFlag.GetEnvVars()))
	for _, e := range envFlag.GetEnvVars() {
		parts = append(parts, "`$"+e+"`")
	}

	return strings.Join(parts, ", ")
}

func visibleCommands(cmds []*cli.Command) []*cli.Command {
	out := make([]*cli.Command, 0, len(cmds))
	for _, c := range cmds {
		if c.Hidden {
			continue
		}

		out = append(out, c)
	}

	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })

	return out
}

// slug turns a command name into an anchor-safe identifier.
func slug(name string) string {
	var b strings.Builder //nolint:varnamelen // idiomatic short name (testing/http/io conventions).

	for _, r := range strings.ToLower(name) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-':
			b.WriteRune(r)
		case r == ' ', r == '_':
			b.WriteRune('-')
		}
	}

	return b.String()
}

// escapeCell renders a string for a markdown table cell. Pipe and
// newline characters break the row, so they get escaped / collapsed.
func escapeCell(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "|", `\|`)

	return s
}

func escapeText(s string) string {
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	s = strings.ReplaceAll(s, "*", `\*`)

	return s
}
