// SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government
// SPDX-License-Identifier: EUPL-1.2 OR GPL-3.0-or-later

package archguard

import (
	"io/fs"
	"runtime"
	"strings"
	"testing"
)

// The eligibility guard passes on a clean tree, which is the state a guard is
// least trustworthy in: a detector that finds nothing looks exactly like a
// detector that cannot find anything. These fixtures feed its four helpers the
// shapes they are supposed to catch, and the near-misses they must not.

func TestBuildConstraintOf_ReadsOnlyRealConstraintLines(t *testing.T) {
	t.Parallel()

	for _, tc := range []struct {
		name   string
		source string
		want   string
		why    string
	}{
		{
			name: "constraint above the package clause", want: "linux",
			source: "//go:build linux\n\npackage p\n",
			why:    "the ordinary form",
		},
		{
			name: "negated and combined", want: "!linux && !windows",
			source: "//go:build !linux && !windows\n\npackage p\n",
			why:    "the whole expression is the declaration, not just the first tag",
		},
		{
			name: "after a licence header", want: "unix",
			source: "// SPDX-FileCopyrightText: 2026 Example\n\n//go:build unix\n\npackage p\n",
			why:    "this repository puts a licence header first, so the constraint is never line one",
		},
		{
			name: "no constraint", want: "",
			source: "// a doc comment\npackage p\n",
			why:    "an ordinary file",
		},
		{
			name: "constraint-looking text after the package clause", want: "",
			source: "package p\n\n//go:build linux\nvar x = 1\n",
			why:    "the toolchain ignores it there, and so must this",
		},
		{
			name: "constraint inside a string literal", want: "",
			source: "package p\n\nvar tmpl = `//go:build linux`\n",
			why:    "data that mentions a constraint is not a constraint",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			got, ok := buildConstraintOf(t, "fixture.go", tc.source)
			if got != tc.want || ok != (tc.want != "") {
				t.Errorf("got (%q, %v), want %q: %s", got, ok, tc.want, tc.why)
			}
		})
	}
}

func TestSatisfiedByCurrentBuild_AgreesWithTheToolchain(t *testing.T) {
	t.Parallel()

	for _, tc := range []struct {
		expr string
		want bool
	}{
		{runtime.GOOS, true},
		{"!" + runtime.GOOS, false},
		{runtime.GOOS + " || plan9", true},
		{runtime.GOOS + " && plan9", false},
		{"!" + runtime.GOOS + " && !plan9", false},
		{runtime.GOARCH, true},
		{"some_tag_nobody_sets", false},
	} {
		t.Run(strings.ReplaceAll(tc.expr, " ", "_"), func(t *testing.T) {
			t.Parallel()

			if got := satisfiedByCurrentBuild(t, tc.expr); got != tc.want {
				t.Errorf("%q evaluated to %v under GOOS=%s, want %v", tc.expr, got, runtime.GOOS, tc.want)
			}
		})
	}
}

func TestEnvironmentReadsIn_FindsThePackageCallsAndNotLookalikes(t *testing.T) {
	t.Parallel()

	source := `package p

import "os"

type cfg struct{}

func (cfg) Getenv(string) string { return "" }

func direct() string  { return os.Getenv("A") }
func lookup() (string, bool) { return os.LookupEnv("B") }
func all() []string   { return os.Environ() }
func write() error    { return os.Setenv("C", "d") }
func clear() error    { return os.Unsetenv("C") }
func low() (string, bool) { return syscall.Getenv("E") }

func method(c cfg) string { return c.Getenv("F") }
func local() string  { return readFile("os.Getenv") }
func readFile(s string) string { return s }
`

	got := environmentReadsIn(t, "fixture.go", source)
	want := []string{"os.Environ", "os.Getenv", "os.LookupEnv", "os.Setenv", "os.Unsetenv", "syscall.Getenv"}

	if len(got) != len(want) {
		t.Fatalf("got %v, want %v", got, want)
	}

	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("got %v, want %v", got, want)
		}
	}

	// The two lookalikes above are the point: a method named Getenv on an
	// application type, and the string "os.Getenv" passed as data. Neither
	// appears in the result, and the counts prove it.
}

func TestHasGeneratedMarker_MatchesTheToolchainConvention(t *testing.T) {
	t.Parallel()

	for _, tc := range []struct {
		name   string
		source string
		want   bool
	}{
		{"canonical", "// Code generated by stringer. DO NOT EDIT.\n\npackage p\n", true},
		{"after a licence header", "// SPDX-FileCopyrightText: 2026 Example\n// Code generated by x. DO NOT EDIT.\n\npackage p\n", true},
		{"missing the do-not-edit half", "// Code generated by stringer.\n\npackage p\n", false},
		{"after the package clause", "package p\n\n// Code generated by x. DO NOT EDIT.\n", false},
		{"prose about generated code", "// This file is generated. DO NOT EDIT.\n\npackage p\n", false},
		{"ordinary file", "// a doc comment\npackage p\n", false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			if got := hasGeneratedMarker(tc.source); got != tc.want {
				t.Errorf("hasGeneratedMarker = %v, want %v", got, tc.want)
			}
		})
	}
}

// isProductGoFile is now the single filter every guard in this package shares,
// so what it admits is a property of all of them at once. That makes it worth a
// fixture: the seven copies it replaced were each capable of drifting alone,
// and one that had drifted would have kept passing while covering less.
func TestIsProductGoFile_AdmitsProductGoAndNothingElse(t *testing.T) {
	t.Parallel()

	for _, tc := range []struct {
		name string
		path string
		dir  bool
		want bool
	}{
		{"product file", "internal/app/version/bump.go", false, true},
		{"product file by base name", "bump.go", false, true},
		{"nested product file", "internal/adapters/git/read.go", false, true},
		{"test file", "internal/app/version/bump_test.go", false, false},
		{"test file by base name", "bump_test.go", false, false},
		{"an internal test file", "internal/cli/deps_internal_test.go", false, false},
		{"a directory", "internal/app/version", true, false},
		{"a directory named like a go file", "weird.go", true, false},
		{"not Go at all", "internal/app/version/README.md", false, false},
		{"go in the middle of the name", "internal/app/gopher.md", false, false},
		{"a file whose name ends in go without a dot", "internal/app/cargo", false, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			if got := isProductGoFile(fixtureDirEntry{name: tc.path, dir: tc.dir}, tc.path); got != tc.want {
				t.Errorf("isProductGoFile(%q, dir=%v) = %v, want %v", tc.path, tc.dir, got, tc.want)
			}
		})
	}
}

type fixtureDirEntry struct {
	name string
	dir  bool
}

func (e fixtureDirEntry) Name() string               { return e.name }
func (e fixtureDirEntry) IsDir() bool                { return e.dir }
func (e fixtureDirEntry) Type() fs.FileMode          { return 0 }
func (e fixtureDirEntry) Info() (fs.FileInfo, error) { return nil, nil } //nolint:nilnil // fixture; Info is never called.
