// SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government
// SPDX-License-Identifier: CC0-1.0

// Package mockbinary writes shell-script stubs to a temp directory and
// prepends that directory to PATH for the duration of the test. Replaces
// the bats `create_mock_binary` helper.
//
// Each invocation of a stub writes a JSON record (argv, env, stdin, cwd)
// to a side-channel file; the test inspects Invocations(name) to assert
// what was called and how.
package mockbinary

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"testing"
)

// Mock manages a t.TempDir() containing shell stubs and a recordings file.
type Mock struct {
	t        *testing.T
	binDir   string
	recPath  string
	mu       sync.Mutex
	prevPath string
}

// New creates a Mock, prepends its bin dir to PATH, and registers cleanup.
func New(t *testing.T) *Mock {
	t.Helper()
	dir := t.TempDir()
	binDir := filepath.Join(dir, "bin")
	if err := os.MkdirAll(binDir, 0o755); err != nil {
		t.Fatalf("mockbinary: mkdir: %v", err)
	}
	recPath := filepath.Join(dir, "invocations.jsonl")
	if err := os.WriteFile(recPath, nil, 0o644); err != nil {
		t.Fatalf("mockbinary: create recordings: %v", err)
	}

	m := &Mock{
		t:        t,
		binDir:   binDir,
		recPath:  recPath,
		prevPath: os.Getenv("PATH"),
	}
	t.Setenv("PATH", binDir+string(os.PathListSeparator)+m.prevPath)
	t.Setenv("MOCKBINARY_RECPATH", recPath)
	t.Cleanup(m.cleanup)
	return m
}

// Add writes a stub binary named `name` whose body is `script`. The script
// runs with $0=$name, $1..$N=argv. Stdin is forwarded.
//
// The stub records each invocation to MOCKBINARY_RECPATH before running the
// user-provided script.
func (m *Mock) Add(name, script string) {
	m.t.Helper()
	path := filepath.Join(m.binDir, name)
	stub := fmt.Sprintf(`#!/usr/bin/env bash
# Mock for %q — generated by mockbinary.

# Read stdin (only if available + non-tty) so the recording captures it.
__mockbinary_stdin=""
if [ ! -t 0 ]; then
  __mockbinary_stdin="$(cat || true)"
fi

# Record invocation.
{
  printf '{'
  printf '"name":%%s,' "$(jq -nR --arg s %q '$s')"
  printf '"args":%%s,' "$(printf '%%s\n' "$@" | jq -R . | jq -s -c .)"
  printf '"stdin":%%s,' "$(printf '%%s' "$__mockbinary_stdin" | jq -Rs .)"
  printf '"cwd":%%s'   "$(pwd | jq -Rs .)"
  printf '}\n'
} >> "$MOCKBINARY_RECPATH"

# User-provided body, with stdin re-piped if any.
__mockbinary_script() {
%s
}
if [ -n "$__mockbinary_stdin" ]; then
  printf '%%s' "$__mockbinary_stdin" | __mockbinary_script "$@"
else
  __mockbinary_script "$@"
fi
`, name, name, script)

	if err := os.WriteFile(path, []byte(stub), 0o755); err != nil {
		m.t.Fatalf("mockbinary: write %q: %v", path, err)
	}
}

// Invocation captures one execution of a stub.
type Invocation struct {
	Name  string   `json:"name"`
	Args  []string `json:"args"`
	Stdin string   `json:"stdin"`
	Cwd   string   `json:"cwd"`
}

// Invocations returns all recorded invocations of `name`, in call order.
func (m *Mock) Invocations(name string) []Invocation {
	m.t.Helper()
	m.mu.Lock()
	defer m.mu.Unlock()

	data, err := os.ReadFile(m.recPath)
	if err != nil {
		m.t.Fatalf("mockbinary: read recordings: %v", err)
	}
	var out []Invocation
	for i, line := range strings.Split(string(data), "\n") {
		if line == "" {
			continue
		}
		var inv Invocation
		if err := json.Unmarshal([]byte(line), &inv); err != nil {
			m.t.Fatalf("mockbinary: parse line %d: %v\nline: %s", i+1, err, line)
		}
		if inv.Name == name {
			out = append(out, inv)
		}
	}
	return out
}

// AllNames returns the distinct stub names that were invoked at least once.
func (m *Mock) AllNames() []string {
	m.t.Helper()
	m.mu.Lock()
	defer m.mu.Unlock()
	data, _ := os.ReadFile(m.recPath)
	seen := map[string]struct{}{}
	for _, line := range strings.Split(string(data), "\n") {
		if line == "" {
			continue
		}
		var inv Invocation
		if json.Unmarshal([]byte(line), &inv) == nil {
			seen[inv.Name] = struct{}{}
		}
	}
	out := make([]string, 0, len(seen))
	for n := range seen {
		out = append(out, n)
	}
	sort.Strings(out)
	return out
}

// Path returns the absolute path of a stub. Useful when the test code wants
// to invoke it directly instead of relying on PATH lookup.
func (m *Mock) Path(name string) string {
	return filepath.Join(m.binDir, name)
}

func (m *Mock) cleanup() {
	// PATH and MOCKBINARY_RECPATH are restored by t.Setenv automatically.
}
