// SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government
// SPDX-License-Identifier: EUPL-1.2 OR GPL-3.0-or-later

// Package mockbinary writes shell-script stubs to a temp directory and
// prepends that directory to PATH for the duration of the test. Replaces
// the bats `create_mock_binary` helper.
//
// Each invocation of a stub appends a NUL-delimited record (name, cwd, argv,
// stdin) to a side-channel file; the test inspects Invocations(name) to assert
// what was called and how.
//
// The recording is lossless for arguments. It used to build JSON with jq, and
// that encoding lost three things quietly: an argument containing a newline
// was recorded as two arguments, a call with no arguments was recorded as one
// empty argument, and every cwd carried a trailing newline. None of them
// failed loudly — they produced a plausible-looking recording of something
// that did not happen, in the double 23 packages assert their argv through.
// Dropping jq also drops a host dependency the suite never installed.
package mockbinary

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"
	"testing"
)

// Mock manages a t.TempDir() containing shell stubs and a recordings file.
type Mock struct {
	t interface {
		Helper()
		Fatalf(format string, args ...any)
	}
	binDir   string
	recPath  string
	mu       sync.Mutex
	prevPath string
}

// New creates a Mock, prepends its bin dir to PATH, and registers cleanup.
func New(t *testing.T) *Mock {
	t.Helper()
	dir := t.TempDir()

	binDir := filepath.Join(dir, "bin")
	if err := os.MkdirAll(binDir, 0o755); err != nil { //nolint:gosec // test infra; binDir is t.TempDir()-based.
		t.Fatalf("mockbinary: mkdir: %v", err)
	}

	recPath := filepath.Join(dir, "invocations.jsonl")
	if err := os.WriteFile(recPath, nil, 0o644); err != nil { //nolint:gosec // test infra; recPath is t.TempDir()-based.
		t.Fatalf("mockbinary: create recordings: %v", err)
	}

	m := &Mock{ //nolint:varnamelen // idiomatic short name (testing/http/io conventions).
		t:        t,
		binDir:   binDir,
		recPath:  recPath,
		prevPath: os.Getenv("PATH"),
	}
	t.Setenv("PATH", binDir+string(os.PathListSeparator)+m.prevPath)
	t.Setenv("MOCKBINARY_RECPATH", recPath)
	t.Cleanup(m.cleanup)

	return m
}

// Add writes a stub binary named `name` whose body is `script`. The script
// runs with $0=$name, $1..$N=argv. Stdin is forwarded. An empty script is a
// stub that succeeds.
//
// The stub records each invocation to MOCKBINARY_RECPATH before running the
// user-provided script.
func (m *Mock) Add(name, script string) {
	m.t.Helper()

	// bash refuses an empty function body, so an empty script used to record
	// the call and then exit 2 with a syntax error.
	if strings.TrimSpace(script) == "" {
		script = ":"
	}

	path := filepath.Join(m.binDir, name)
	stub := fmt.Sprintf(`#!/usr/bin/env bash
# Mock for %q — generated by mockbinary.

# Read stdin (only if available + non-tty) so the recording captures it.
#
# The trailing "x" is not decoration. Command substitution strips every
# trailing newline, so "$(cat)" recorded a piped "payload\n\n\n" as
# "payload" — and a test asserting what it piped to a tool would be
# asserting something the tool never received. Appending a byte that is not
# a newline leaves nothing for the stripping to take, and the byte is then
# removed here.
__mockbinary_stdin=""
if [ ! -t 0 ]; then
  __mockbinary_stdin="$(cat; printf 'x' || true)"
  __mockbinary_stdin="${__mockbinary_stdin%%x}"
fi

# One invocation is one NUL-delimited record, written by a single printf:
#
#   name \0 cwd \0 argc \0 arg1 \0 ... argN \0 stdin \0
#
# NUL is the only byte that cannot occur in an argument, so splitting on it
# loses nothing, and the argc field makes the record self-delimiting, which
# is what lets an argument contain a newline.
#
# Records are NOT atomic against each other. bash's printf writes once per
# conversion, so a record reaches the file as one write per field and two
# stubs running at the same time interleave: 40 concurrent invocations
# produced a file that parsed into 11 records and then a torn one. Making it
# atomic in shell needs either a lock or a framing assembled in a variable
# first, and a variable cannot hold the NUL this framing is built on.
# Neither is worth it for a helper whose callers invoke tools in sequence.
# What matters is that the reader REFUSES a torn file rather than turning it
# into invocations nobody made, which it does.
printf '%%s\0' %q "$PWD" "$#" "$@" "$__mockbinary_stdin" >> "$MOCKBINARY_RECPATH"

# User-provided body, with stdin re-piped if any.
__mockbinary_script() {
%s
}
if [ -n "$__mockbinary_stdin" ]; then
  printf '%%s' "$__mockbinary_stdin" | __mockbinary_script "$@"
else
  __mockbinary_script "$@"
fi
`, name, name, script)

	if err := os.WriteFile(path, []byte(stub), 0o755); err != nil { //nolint:gosec // test infra; stub must be exec'able.
		m.t.Fatalf("mockbinary: write %q: %v", path, err)
	}
}

// Invocation captures one execution of a stub.
//
// Args is exactly the argv the stub received: empty (never a single empty
// string) when the stub was called with no arguments, and one element per
// argument however many newlines it contains. Cwd is the directory the stub
// ran in, with no trailing newline. Stdin is byte-exact including trailing
// newlines.
//
// The one thing not representable is a NUL byte in stdin: bash drops NULs
// when reading into a variable, and NUL is the record separator here in any
// case. Nothing in this repository pipes binary to a stub — the piped inputs
// are commit messages, signing payloads and command scripts — so this is
// stated rather than worked around with a temporary file per invocation.
type Invocation struct {
	Name  string
	Args  []string
	Stdin string
	Cwd   string
}

// Invocations returns all recorded invocations of `name`, in call order.
func (m *Mock) Invocations(name string) []Invocation {
	m.t.Helper()

	m.mu.Lock()
	defer m.mu.Unlock()

	var out []Invocation

	for _, inv := range m.readRecordings() {
		if inv.Name == name {
			out = append(out, inv)
		}
	}

	return out
}

// All returns every recorded invocation across all stubs, in call order.
// Invocations(name) cannot show that one binary ran before a different one,
// which is what an ordered cleanup or teardown sequence is made of.
func (m *Mock) All() []Invocation {
	m.t.Helper()

	m.mu.Lock()
	defer m.mu.Unlock()

	return m.readRecordings()
}

// AllNames returns the distinct stub names that were invoked at least once.
func (m *Mock) AllNames() []string {
	m.t.Helper()

	m.mu.Lock()
	defer m.mu.Unlock()

	seen := map[string]struct{}{}
	for _, inv := range m.readRecordings() {
		seen[inv.Name] = struct{}{}
	}

	out := make([]string, 0, len(seen))
	for n := range seen {
		out = append(out, n)
	}

	sort.Strings(out)

	return out
}

// Path returns the absolute path of a stub. Useful when the test code wants
// to invoke it directly instead of relying on PATH lookup.
func (m *Mock) Path(name string) string {
	return filepath.Join(m.binDir, name)
}

// readRecordings is shared by both assertions so corruption cannot look like
// absence. The caller holds mu.
//
// The wire format is NUL-delimited and self-delimiting: each record is
// name, cwd, argc, argc arguments, stdin. A short or unparsable record is
// fatal rather than skipped — a test that silently saw fewer invocations than
// happened would assert the wrong thing and pass.
func (m *Mock) readRecordings() []Invocation {
	m.t.Helper()

	data, err := os.ReadFile(m.recPath)
	if err != nil {
		m.t.Fatalf("mockbinary: read recordings: %v", err)
	}

	if len(data) == 0 {
		return nil
	}

	fields := strings.Split(string(data), "\x00")

	// A well-formed file ends with a NUL, so Split leaves one trailing "".
	if last := len(fields) - 1; fields[last] != "" {
		m.t.Fatalf("mockbinary: recordings do not end at a record boundary; last field: %q", fields[last])
	} else {
		fields = fields[:last]
	}

	var out []Invocation

	for pos := 0; pos < len(fields); {
		inv, next := m.decodeRecord(fields, pos)
		out = append(out, inv)
		pos = next
	}

	return out
}

// decodeRecord reads one record starting at pos and returns it with the index
// just past it.
func (m *Mock) decodeRecord(fields []string, pos int) (Invocation, int) {
	m.t.Helper()

	// name, cwd, argc, then stdin after the arguments.
	const headerFields = 3

	if pos+headerFields > len(fields) {
		m.t.Fatalf("mockbinary: truncated record header at field %d: %q", pos, fields[pos:])
	}

	name, cwd, rawArgc := fields[pos], fields[pos+1], fields[pos+2]

	if name == "" {
		m.t.Fatalf("mockbinary: missing name at field %d", pos)
	}

	argc, err := strconv.Atoi(rawArgc)
	if err != nil || argc < 0 {
		m.t.Fatalf("mockbinary: bad argument count %q at field %d: %v", rawArgc, pos+2, err)
	}

	// +1 for the stdin field that follows the arguments.
	if pos+headerFields+argc+1 > len(fields) {
		m.t.Fatalf("mockbinary: record for %q claims %d arguments but the file holds %d more fields",
			name, argc, len(fields)-pos-headerFields)
	}

	args := make([]string, argc)
	copy(args, fields[pos+headerFields:pos+headerFields+argc])

	return Invocation{
		Name:  name,
		Args:  args,
		Stdin: fields[pos+headerFields+argc],
		Cwd:   cwd,
	}, pos + headerFields + argc + 1
}

func (m *Mock) cleanup() {
	// PATH and MOCKBINARY_RECPATH are restored by t.Setenv automatically.
}
