# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0
name: Lint Public Code
on: [workflow_call] # yamllint disable-line rule:truthy
permissions:
  contents: read
jobs:
  publiccode_validation:
    name: Publiccode Validation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Validate publiccode metadata
        uses: italia/publiccode-parser-action@0deab88c3f094aa12c5826e52ac2c4f176446821 # v1.6.0
        with:
          publiccode: "publiccode.yml"
