# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0
name: Verify Mise And Just
on: [workflow_call]
permissions:
  contents: read
jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Needed for commit linting
      - name: Setup mise
        uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3
        with:
          install: true
          cache: true
          experimental: true # Required for go backend tools
      - name: Install mise tools
        run: |
          mise install
          mise list
      - name: Just Verify
        env:
          SHELLCHECK_OPTS: --exclude=SC2086
        run: |
          activate_mise() {
            eval "$(mise activate bash)"
          }

          activate_mise
          just lint
