# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0
name: Lint Public Code
on: [workflow_call] # yamllint disable-line rule:truthy
permissions:
  contents: read
jobs:
  publiccode_validation:
    name: Publiccode Validation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Validate publiccode metadata
        uses: italia/publiccode-parser-action@0deab88c3f094aa12c5826e52ac2c4f176446821 # v1.6.0
        with:
          publiccode: "publiccode.yml"
